### PR TITLE
Detect Android emulator for Android setup

### LINKED ISSUE #89: Crash when not setting `deprecatedLegacyRevenueCatAPIKey` on simulator
On 3.5.0 and 3.5.1 versions of purchases-unity, if you test using the simulator, the app will crash with a confusing message saying "Unity error: "NullReferenceException: Object reference not set to an instance of an object". 

The issue stems [from this logic in `setup`](https://github.com/RevenueCat/purchases-unity/blob/main/RevenueCat/Scripts/Purchases.cs#L105), which checks for iOS and Android physical devices, but apparently simulators don't pass the checks.

### PR DESCRIPTION
**Pull request by joshdholtz**
## Motivation
Fixes #89
Some Android emulators were not being detected by the `RuntimePlatform.Android` check

## Description
- Some emulators (not all) are not detected by `Application.platform == RuntimePlatform.Android`
- Adds `IsAndroidEmulator()` function
  - Attempts to initialize an `android.os.Build` class to extract the `FINGERPRINT`
  - If `FINGERPRINT` is `generic` then it should be an Android emulator
  - Wrapped in try/catch because creating `AndroidJavaClass` will fail on iOS

⁉️ Additional thought... We could just get rid of the `FINGERPRINT` and rely on `AndroidJavaClass` because we don't care if its an emulator or not. We only care about it its an Android device 🤷‍♂️

### CODE REVIEW

File: RevenueCat/Scripts/Purchases.cs [hunk 1]
```diff
@@ -114,6 +115,23 @@ private void Setup(string newUserId)
         _wrapper.Setup(gameObject.name, apiKey, newUserId, observerMode, userDefaultsSuiteName);
     }
 
+    public bool IsAndroidEmulator()
+    {
+        try
+        {
+            // From https://stackoverflow.com/questions/51880866/detect-if-game-running-in-android-emulator
+            AndroidJavaClass osBuild;
+            osBuild = new AndroidJavaClass("android.os.Build");
```
Comment (vegaro) [inline RevenueCat/Scripts/Purchases.cs:124]: Can we join it with the declaration of the variable?

File: RevenueCat/Scripts/Purchases.cs [hunk 2]
```diff
@@ -114,6 +115,23 @@ private void Setup(string newUserId)
         _wrapper.Setup(gameObject.name, apiKey, newUserId, observerMode, userDefaultsSuiteName);
     }
 
+    public bool IsAndroidEmulator()
```
Comment (vegaro) [inline RevenueCat/Scripts/Purchases.cs:118]: This can be private right?

Comment (joshdholtz) [reply RevenueCat/Scripts/Purchases.cs:118]: Oh yeah, I meant to change that 🙈

**Review by vegaro — APPROVED** [review]
